
package com.mycompany.plhospital;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.net.InetAddress;
import java.net.Socket;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.Timer;

public class VentanaHospital extends javax.swing.JFrame {

    /**
     * Creates new form VentanaHospital
     */
    JTextField puestosVacunacion[]=new JTextField[10];
    JTextField puestosObservacion[]=new JTextField[20];
    
    public VentanaHospital() {
        initComponents();
        HiloCliente cliente = new HiloCliente(this);
        cliente.start();
        
        
        puestosVacunacion[0]=puestoVacunacion_0;
        puestosVacunacion[1]=puestoVacunacion_1;
        puestosVacunacion[2]=puestoVacunacion_2;
        puestosVacunacion[3]=puestoVacunacion_3;
        puestosVacunacion[4]=puestoVacunacion_4;
        puestosVacunacion[5]=puestoVacunacion_5;
        puestosVacunacion[6]=puestoVacunacion_6;
        puestosVacunacion[7]=puestoVacunacion_7;
        puestosVacunacion[8]=puestoVacunacion_8;
        puestosVacunacion[9]=puestoVacunacion_9;
        
        puestosObservacion[0]=puestoObservacion_0;
        puestosObservacion[1]=puestoObservacion_1;
        puestosObservacion[2]=puestoObservacion_2;
        puestosObservacion[3]=puestoObservacion_3;
        puestosObservacion[4]=puestoObservacion_4;
        puestosObservacion[5]=puestoObservacion_5;
        puestosObservacion[6]=puestoObservacion_6;
        puestosObservacion[7]=puestoObservacion_7;
        puestosObservacion[8]=puestoObservacion_8;
        puestosObservacion[9]=puestoObservacion_9;
        puestosObservacion[10]=puestoObservacion_10;
        puestosObservacion[11]=puestoObservacion_11;
        puestosObservacion[12]=puestoObservacion_12;
        puestosObservacion[13]=puestoObservacion_13;
        puestosObservacion[14]=puestoObservacion_14;
        puestosObservacion[15]=puestoObservacion_15;
        puestosObservacion[16]=puestoObservacion_16;
        puestosObservacion[17]=puestoObservacion_17;
        puestosObservacion[18]=puestoObservacion_18;
        puestosObservacion[19]=puestoObservacion_19;
        
        
        
    }
    
    public void rellenarVentana(String aux1, String aux2, String vacunasDisponibles, String colaEspera, 
            String[] puestosVacunacion, String[] puestosObservacion, String salaDescanso, String pacienteRegistro){
        this.aux1.setText(aux1);
        this.aux2.setText(aux2);
        this.vacunasDisponibles.setText(vacunasDisponibles);
        this.colaEspera.setText(colaEspera);
        this.salaDescanso.setText(salaDescanso);
        this.pacienteRegistro.setText(pacienteRegistro);
        for (int i=0; i<10;i++){
            this.puestosVacunacion[i].setText(puestosVacunacion[i]);
            this.puestosObservacion[i].setText(puestosObservacion[i]);
        }
        for (int i=10; i<20;i++){
            this.puestosObservacion[i].setText(puestosObservacion[i]);
        }
    }
    
    public void enviarPuestoCerrado(int puesto){
        Socket cliente;
        DataOutputStream salida;
        DataInputStream entrada;
        String[] puestosVacunacion = new String[10];
        String[] puestosObservacion = new String[20];
        
        try {
            cliente = new Socket(InetAddress.getLocalHost(),5000);
            salida = new DataOutputStream(cliente.getOutputStream());
            entrada = new DataInputStream(cliente.getInputStream());  //Creamos los canales de entrada/salida
            String aux1 = entrada.readUTF();
            String aux2 = entrada.readUTF();
            String vacunasDisponibles = entrada.readUTF();
            String colaEspera= entrada.readUTF();
            for (int i=0;i<10;i++){
                puestosVacunacion[i]=entrada.readUTF();
            }
            for (int i=0;i<20;i++){
                puestosObservacion[i]=entrada.readUTF();
            }
            String salaDescanso=entrada.readUTF();
            String pacienteRegistro=entrada.readUTF();
        salida.writeInt(puesto);
        cliente.close();  
        } catch (IOException ex) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        colaEspera = new javax.swing.JTextField();
        aux1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        puestoVacunacion_8 = new javax.swing.JTextField();
        puestoVacunacion_0 = new javax.swing.JTextField();
        puestoVacunacion_5 = new javax.swing.JTextField();
        puestoVacunacion_7 = new javax.swing.JTextField();
        puestoVacunacion_9 = new javax.swing.JTextField();
        puestoVacunacion_6 = new javax.swing.JTextField();
        puestoVacunacion_4 = new javax.swing.JTextField();
        puestoVacunacion_2 = new javax.swing.JTextField();
        puestoVacunacion_3 = new javax.swing.JTextField();
        puestoVacunacion_1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        salaDescanso = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        puestoObservacion_3 = new javax.swing.JTextField();
        puestoObservacion_6 = new javax.swing.JTextField();
        puestoObservacion_0 = new javax.swing.JTextField();
        puestoObservacion_1 = new javax.swing.JTextField();
        puestoObservacion_4 = new javax.swing.JTextField();
        puestoObservacion_2 = new javax.swing.JTextField();
        puestoObservacion_5 = new javax.swing.JTextField();
        puestoObservacion_7 = new javax.swing.JTextField();
        puestoObservacion_8 = new javax.swing.JTextField();
        puestoObservacion_11 = new javax.swing.JTextField();
        puestoObservacion_9 = new javax.swing.JTextField();
        puestoObservacion_10 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        puestoObservacion_14 = new javax.swing.JTextField();
        puestoObservacion_13 = new javax.swing.JTextField();
        puestoObservacion_12 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        puestoObservacion_15 = new javax.swing.JTextField();
        puestoObservacion_16 = new javax.swing.JTextField();
        puestoObservacion_17 = new javax.swing.JTextField();
        aux2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        vacunasDisponibles = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        puestoObservacion_19 = new javax.swing.JTextField();
        puestoObservacion_18 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        ButtPuesto9 = new javax.swing.JButton();
        ButtPuesto0 = new javax.swing.JButton();
        ButtPuesto1 = new javax.swing.JButton();
        ButtPuesto2 = new javax.swing.JButton();
        ButtPuesto3 = new javax.swing.JButton();
        ButtPuesto4 = new javax.swing.JButton();
        ButtPuesto6 = new javax.swing.JButton();
        ButtPuesto8 = new javax.swing.JButton();
        ButtPuesto5 = new javax.swing.JButton();
        ButtPuesto7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pacienteRegistro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOSPITAL");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("SALA DE ESPERA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("SALA DE DESCANSO PERSONAL SANITARIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 472, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("SALA DE OBSERVACIÓN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 472, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("SALA DE VACUNACIÓN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 241, -1, -1));

        colaEspera.setEditable(false);
        colaEspera.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(colaEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 62, 812, 30));

        aux1.setEditable(false);
        getContentPane().add(aux1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 90, -1));

        jLabel2.setText("Auxiliar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 126, -1, -1));

        jLabel6.setText("Paciente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 152, -1, -1));

        jLabel7.setText("Puesto 0");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 274, -1, -1));

        jLabel8.setText("Puesto 2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 274, -1, -1));

        jLabel9.setText("Puesto 1");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        jLabel10.setText("Puesto 3");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 333, -1, -1));

        jLabel11.setText("Puesto 4");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 231, -1, -1));

        jLabel12.setText("Puesto 5");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 231, -1, -1));

        jLabel13.setText("Puesto 6");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 301, -1, -1));

        jLabel14.setText("Puesto 7");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 301, -1, -1));

        jLabel15.setText("Puesto 8");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 377, -1, -1));

        jLabel16.setText("Puesto 9");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 377, -1, -1));

        puestoVacunacion_8.setEditable(false);
        getContentPane().add(puestoVacunacion_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 404, 130, -1));

        puestoVacunacion_0.setEditable(false);
        getContentPane().add(puestoVacunacion_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, -1));

        puestoVacunacion_5.setEditable(false);
        getContentPane().add(puestoVacunacion_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 258, 139, -1));

        puestoVacunacion_7.setEditable(false);
        getContentPane().add(puestoVacunacion_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 328, 139, -1));

        puestoVacunacion_9.setEditable(false);
        getContentPane().add(puestoVacunacion_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 404, 139, -1));

        puestoVacunacion_6.setEditable(false);
        getContentPane().add(puestoVacunacion_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 328, 130, -1));

        puestoVacunacion_4.setEditable(false);
        getContentPane().add(puestoVacunacion_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 258, 130, -1));

        puestoVacunacion_2.setEditable(false);
        getContentPane().add(puestoVacunacion_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 296, 130, -1));

        puestoVacunacion_3.setEditable(false);
        getContentPane().add(puestoVacunacion_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 360, 139, -1));

        puestoVacunacion_1.setEditable(false);
        getContentPane().add(puestoVacunacion_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 359, 139, -1));

        jLabel17.setText("Cola de espera:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        salaDescanso.setEditable(false);
        getContentPane().add(salaDescanso, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 506, 306, 261));

        jLabel18.setText("Puesto 0");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 501, -1, -1));

        jLabel19.setText("Puesto 3");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 554, -1, -1));

        jLabel20.setText("Puesto 6");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 606, -1, -1));

        puestoObservacion_3.setEditable(false);
        getContentPane().add(puestoObservacion_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 574, 137, -1));

        puestoObservacion_6.setEditable(false);
        getContentPane().add(puestoObservacion_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 628, 137, -1));

        puestoObservacion_0.setEditable(false);
        getContentPane().add(puestoObservacion_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 524, 137, -1));

        puestoObservacion_1.setEditable(false);
        getContentPane().add(puestoObservacion_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 524, 137, -1));

        puestoObservacion_4.setEditable(false);
        getContentPane().add(puestoObservacion_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 576, 137, -1));

        puestoObservacion_2.setEditable(false);
        getContentPane().add(puestoObservacion_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 524, 137, -1));

        puestoObservacion_5.setEditable(false);
        getContentPane().add(puestoObservacion_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 576, 137, -1));

        puestoObservacion_7.setEditable(false);
        getContentPane().add(puestoObservacion_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 628, 137, -1));

        puestoObservacion_8.setEditable(false);
        getContentPane().add(puestoObservacion_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 628, 137, -1));

        puestoObservacion_11.setEditable(false);
        getContentPane().add(puestoObservacion_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 678, 137, -1));

        puestoObservacion_9.setEditable(false);
        getContentPane().add(puestoObservacion_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 678, 137, -1));

        puestoObservacion_10.setEditable(false);
        getContentPane().add(puestoObservacion_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 679, 137, -1));

        jLabel21.setText("Puesto 9");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 658, -1, -1));

        jLabel22.setText("Puesto 12");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 709, -1, -1));

        puestoObservacion_14.setEditable(false);
        getContentPane().add(puestoObservacion_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 732, 137, -1));

        puestoObservacion_13.setEditable(false);
        getContentPane().add(puestoObservacion_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 732, 137, -1));

        puestoObservacion_12.setEditable(false);
        getContentPane().add(puestoObservacion_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 732, 137, -1));

        jLabel23.setText("Puesto 18");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 812, -1, -1));

        puestoObservacion_15.setEditable(false);
        getContentPane().add(puestoObservacion_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 782, 137, -1));

        puestoObservacion_16.setEditable(false);
        getContentPane().add(puestoObservacion_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 782, 137, -1));

        puestoObservacion_17.setEditable(false);
        getContentPane().add(puestoObservacion_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 782, 137, -1));

        aux2.setEditable(false);
        getContentPane().add(aux2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 283, 84, -1));

        jLabel25.setText("<html><body>Vacunas <br>disponibles: </body></html>\"");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel25.setAutoscrolls(true);
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 312, 84, -1));

        jLabel24.setText("Auxiliar");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 263, -1, -1));

        vacunasDisponibles.setEditable(false);
        getContentPane().add(vacunasDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 84, -1));

        jLabel26.setText("Puesto 15");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 762, -1, -1));

        puestoObservacion_19.setEditable(false);
        getContentPane().add(puestoObservacion_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 832, 137, -1));

        puestoObservacion_18.setEditable(false);
        getContentPane().add(puestoObservacion_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 832, 137, -1));

        jTextField38.setBackground(new java.awt.Color(204, 204, 255));
        jTextField38.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField38.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 193, 470, 20));

        jTextField39.setBackground(new java.awt.Color(204, 204, 255));
        jTextField39.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 443, 580, 20));

        jTextField40.setBackground(new java.awt.Color(204, 204, 255));
        jTextField40.setForeground(new java.awt.Color(255, 255, 204));
        jTextField40.setToolTipText("");
        jTextField40.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 443, 223, 20));

        jTextField41.setBackground(new java.awt.Color(204, 204, 255));
        jTextField41.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 453, 20, 410));

        jLabel27.setText("Puesto 2");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 501, -1, -1));

        jLabel28.setText("Puesto 1");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 501, -1, -1));

        jLabel29.setText("Puesto 5");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 559, -1, -1));

        jLabel30.setText("Puesto 4");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 559, -1, -1));

        jLabel31.setText("Puesto 8");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 611, -1, -1));

        jLabel32.setText("Puesto 10");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 658, -1, -1));

        jLabel33.setText("Puesto 7");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 611, -1, -1));

        jLabel34.setText("Puesto 11");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 658, -1, -1));

        jLabel35.setText("Puesto 14");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 709, -1, -1));

        jLabel36.setText("Puesto 13");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 708, -1, -1));

        jLabel37.setText("Puesto 16");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 767, -1, -1));

        jLabel38.setText("Puesto 17");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 767, -1, -1));

        jLabel39.setText("Puesto 19");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 812, -1, -1));

        jTextField43.setBackground(new java.awt.Color(204, 204, 255));
        jTextField43.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField43.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 193, 320, 20));

        ButtPuesto9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto9.setText("CERRAR");
        ButtPuesto9.setAlignmentY(0.0F);
        ButtPuesto9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto9ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 70, -1));

        ButtPuesto0.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto0.setText("CERRAR");
        ButtPuesto0.setAlignmentY(0.0F);
        ButtPuesto0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto0ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto0, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 70, -1));

        ButtPuesto1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto1.setText("CERRAR");
        ButtPuesto1.setAlignmentY(0.0F);
        ButtPuesto1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 70, -1));

        ButtPuesto2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto2.setText("CERRAR");
        ButtPuesto2.setAlignmentY(0.0F);
        ButtPuesto2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto2ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 70, -1));

        ButtPuesto3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto3.setText("CERRAR");
        ButtPuesto3.setAlignmentY(0.0F);
        ButtPuesto3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto3ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 70, -1));

        ButtPuesto4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto4.setText("CERRAR");
        ButtPuesto4.setAlignmentY(0.0F);
        ButtPuesto4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto4ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 70, -1));

        ButtPuesto6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto6.setText("CERRAR");
        ButtPuesto6.setAlignmentY(0.0F);
        ButtPuesto6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto6ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 70, -1));

        ButtPuesto8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto8.setText("CERRAR");
        ButtPuesto8.setAlignmentY(0.0F);
        ButtPuesto8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto8ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 70, -1));

        ButtPuesto5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto5.setText("CERRAR");
        ButtPuesto5.setAlignmentY(0.0F);
        ButtPuesto5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto5ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 70, -1));

        ButtPuesto7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ButtPuesto7.setText("CERRAR");
        ButtPuesto7.setAlignmentY(0.0F);
        ButtPuesto7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtPuesto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtPuesto7ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtPuesto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 70, -1));

        jPanel1.setBackground(new java.awt.Color(252, 224, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pacienteRegistro.setEditable(false);
        jPanel1.add(pacienteRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 150, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtPuesto0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto0ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(0);
    }//GEN-LAST:event_ButtPuesto0ActionPerformed

    private void ButtPuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto1ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(1);
    }//GEN-LAST:event_ButtPuesto1ActionPerformed

    private void ButtPuesto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto2ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(2);
    }//GEN-LAST:event_ButtPuesto2ActionPerformed

    private void ButtPuesto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto3ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(3);
    }//GEN-LAST:event_ButtPuesto3ActionPerformed

    private void ButtPuesto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto4ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(4);
    }//GEN-LAST:event_ButtPuesto4ActionPerformed

    private void ButtPuesto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto6ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(6);
    }//GEN-LAST:event_ButtPuesto6ActionPerformed

    private void ButtPuesto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto8ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(8);
    }//GEN-LAST:event_ButtPuesto8ActionPerformed

    private void ButtPuesto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto5ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(5);
    }//GEN-LAST:event_ButtPuesto5ActionPerformed

    private void ButtPuesto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto7ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(7);
    }//GEN-LAST:event_ButtPuesto7ActionPerformed

    private void ButtPuesto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtPuesto9ActionPerformed
        // TODO add your handling code here:
        enviarPuestoCerrado(9);
    }//GEN-LAST:event_ButtPuesto9ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaHospital().setVisible(true);
                
            }
        });
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtPuesto0;
    private javax.swing.JButton ButtPuesto1;
    private javax.swing.JButton ButtPuesto2;
    private javax.swing.JButton ButtPuesto3;
    private javax.swing.JButton ButtPuesto4;
    private javax.swing.JButton ButtPuesto5;
    private javax.swing.JButton ButtPuesto6;
    private javax.swing.JButton ButtPuesto7;
    private javax.swing.JButton ButtPuesto8;
    private javax.swing.JButton ButtPuesto9;
    private javax.swing.JTextField aux1;
    private javax.swing.JTextField aux2;
    private javax.swing.JTextField colaEspera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField pacienteRegistro;
    private javax.swing.JTextField puestoObservacion_0;
    private javax.swing.JTextField puestoObservacion_1;
    private javax.swing.JTextField puestoObservacion_10;
    private javax.swing.JTextField puestoObservacion_11;
    private javax.swing.JTextField puestoObservacion_12;
    private javax.swing.JTextField puestoObservacion_13;
    private javax.swing.JTextField puestoObservacion_14;
    private javax.swing.JTextField puestoObservacion_15;
    private javax.swing.JTextField puestoObservacion_16;
    private javax.swing.JTextField puestoObservacion_17;
    private javax.swing.JTextField puestoObservacion_18;
    private javax.swing.JTextField puestoObservacion_19;
    private javax.swing.JTextField puestoObservacion_2;
    private javax.swing.JTextField puestoObservacion_3;
    private javax.swing.JTextField puestoObservacion_4;
    private javax.swing.JTextField puestoObservacion_5;
    private javax.swing.JTextField puestoObservacion_6;
    private javax.swing.JTextField puestoObservacion_7;
    private javax.swing.JTextField puestoObservacion_8;
    private javax.swing.JTextField puestoObservacion_9;
    private javax.swing.JTextField puestoVacunacion_0;
    private javax.swing.JTextField puestoVacunacion_1;
    private javax.swing.JTextField puestoVacunacion_2;
    private javax.swing.JTextField puestoVacunacion_3;
    private javax.swing.JTextField puestoVacunacion_4;
    private javax.swing.JTextField puestoVacunacion_5;
    private javax.swing.JTextField puestoVacunacion_6;
    private javax.swing.JTextField puestoVacunacion_7;
    private javax.swing.JTextField puestoVacunacion_8;
    private javax.swing.JTextField puestoVacunacion_9;
    private javax.swing.JTextField salaDescanso;
    private javax.swing.JTextField vacunasDisponibles;
    // End of variables declaration//GEN-END:variables

    
}